version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: mysuperdatacompany
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  migrate:
    build: .
    command: python manage.py migrate
    volumes:
      - .:/code
    depends_on:
      - db
