# Generated by Django 5.0.6 on 2024-06-18 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataupload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datarecord',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dataupload.fileupload'),
        ),
    ]
